import { FormEvent, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { apiClient } from '@/lib/api-client';
interface Account { id: string; name: string; }
interface Transaction { id: string; accountId: string; type: string; amountCents: string; description: string | null; transactionDate: string; status: string; }
const money = (value: string) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(value) / 100);
export function TransactionsPage() {
  const client = useQueryClient(); const [accountId, setAccountId] = useState(''); const [type, setType] = useState('EXPENSE'); const [amount, setAmount] = useState(''); const [description, setDescription] = useState(''); const [date, setDate] = useState(new Date().toISOString().slice(0, 10));
  const accounts = useQuery({ queryKey: ['accounts'], queryFn: () => apiClient.get<Account[]>('/accounts') });
  const transactions = useQuery({ queryKey: ['transactions'], queryFn: () => apiClient.get<Transaction[]>('/transactions') });
  const create = useMutation({ mutationFn: () => apiClient.post('/transactions', { accountId, type, amountCents: Math.round(Number(amount.replace(',', '.')) * 100), description: description || undefined, transactionDate: date }), onSuccess: () => { setAmount(''); setDescription(''); void client.invalidateQueries({ queryKey: ['transactions'] }); } });
  const submit = (event: FormEvent) => { event.preventDefault(); create.mutate(); };
  return <div><h1 className="text-2xl font-semibold text-ink">Transactions</h1><p className="mt-1 text-sm text-muted">Record income, expenses and transfers in cents-safe amounts.</p><form onSubmit={submit} className="mt-8 grid gap-3 rounded-lg border border-line bg-panel p-5 sm:grid-cols-3"><select required value={accountId} onChange={(e) => setAccountId(e.target.value)} className="rounded-md border border-line bg-surface px-3 py-2 text-sm text-ink"><option value="">Select account</option>{accounts.data?.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</select><select value={type} onChange={(e) => setType(e.target.value)} className="rounded-md border border-line bg-surface px-3 py-2 text-sm text-ink"><option value="EXPENSE">Expense</option><option value="INCOME">Income</option><option value="TRANSFER">Transfer</option></select><input required value={amount} onChange={(e) => setAmount(e.target.value)} inputMode="decimal" placeholder="Amount" className="rounded-md border border-line bg-surface px-3 py-2 text-sm text-ink" /><input value={description} onChange={(e) => setDescription(e.target.value)} placeholder="Description" className="rounded-md border border-line bg-surface px-3 py-2 text-sm text-ink" /><input required type="date" value={date} onChange={(e) => setDate(e.target.value)} className="rounded-md border border-line bg-surface px-3 py-2 text-sm text-ink" /><button disabled={create.isPending || !accounts.data?.length} className="rounded-md bg-accent px-4 py-2 text-sm font-semibold text-white">Add transaction</button></form><div className="mt-6 overflow-hidden rounded-lg border border-line bg-panel"><table className="w-full text-left text-sm"><thead className="border-b border-line text-muted"><tr><th className="px-5 py-3">Date</th><th className="px-5 py-3">Type</th><th className="px-5 py-3">Description</th><th className="px-5 py-3">Amount</th></tr></thead><tbody>{transactions.data?.map((t) => <tr key={t.id} className="border-b border-line last:border-0"><td className="px-5 py-3 text-muted">{t.transactionDate}</td><td className="px-5 py-3 text-muted">{t.type}</td><td className="px-5 py-3 text-ink">{t.description ?? '—'}</td><td className="px-5 py-3 text-ink">{money(t.amountCents)}</td></tr>)}</tbody></table>{transactions.isLoading && <p className="p-5 text-sm text-muted">Loading transactions...</p>}{transactions.data?.length === 0 && <p className="p-5 text-sm text-muted">No transactions yet.</p>}</div></div>;
}
